email_handler.py
I think `250` is when we successfully forward the email, in this case, the email is not forwarded but we refuse to do so, thus `450` is more consistent.
=> change the smtp response code

.dockerignore, README.md, app/config.py, app/dns_utils.py
- Use CloudFlare DNS nameserver 1.1.1.1
- Replace 1.1.1.0/24 by 240.0.0.0/24 in docker network: 240.0.0.0/4 is a reserved IP https://en.wikipedia.org/wiki/Reserved_IP_addresses
=> Use Cloudflare DNS nameserver

email_handler.py
Until now the catch-all can only be used on custom domain this is *different* to the default alias domain.
With this PR, one can import the default domain as custom domain and enable the catch-all option on it.
=> Allow catch-all on the alias default domain

app/dashboard/templates/dashboard/custom_alias.html, app/dashboard/views/custom_alias.py
This PR uses the same UI for alias creation as on the extension: if user has several domain, the domains would be displayed as a dropdown list.
The design is similar to this mockup:
This PR servers also as a preparation for adding the support for having several alias domains. Currently free user could only use `simplelogin.co` domain, the idea is to add other domains owned by SimpleLogin to this list. This mitigates the case where `simplelogin.co` is blacklisted in the future.
=> New custom alias ui

.dockerignore, Dockerfile
* reduce number of layers
* remove vim installation (I'm guessing it was here for debug purposes, also this is not a good way to install a package in Docker)
* add LICENSE and README to .dockerignore
* don't cache with pip
* add missing EXPOSE directive
This set of changes reduces the image size by almost 100 Mb!
As a side note, I would recommend renaming this repo to something more meaningful than `app`. When cloning a repo, the organization doesn't appear, only the repo name. In my `$dev` folder, I have several repositories, and their name is the name of the application, imagine if they were all called `app` ;)
Cheers
~Nico
=> Improve the Dockerfile

email_handler.py
If in original message no name is present, email is forwarded like this:
**- hi at simplelogin.io**
This commit adds a conditional to hide the unnecessary seperator.
**hi at simplelogin.io**
Not runtime tested.
=> Hide seperator from 'from header' if no name present

cron.py
i.e. users who:
1. has lifetime licence or active subscription and
2. is in trial period
=> only send trial-end email to user who is in trial

app/extensions.py, server.py
Currently firefox displays this warning:
```
Cookie “slapp” will be soon rejected because it has the “sameSite” attribute set to
“none” or an invalid value, without the “secure” attribute.
To know more about the “sameSite“ attribute,
read https://developer.mozilla.org/docs/Web/HTTP/Cookies
```
- This commit sets the 'secure' flag to true when the base url starts with https
- Set the SameSite attribute to 'strict'
- Set Flask session_protection to 'strong' (see https://flask-login.readthedocs.io/en/latest/#session-protection)
=> Session cookie flags.

app/auth/views/fido.py, app/dashboard/views/fido_setup.py
- User may not have a name - didn't realize this since the local fake data have it as default
- user_verification should be discouraged to work on iOS
=> 🐛 WebAuthn bug fixes

app/dashboard/templates/dashboard/alias_log.html, app/dashboard/templates/dashboard/index.html, app/dashboard/views/index.py, static/assets/css/darkmode.css, static/assets/js/core.js, static/assets/js/theme.js, templates/base.html, templates/footer.html
1. **When using the dark theme, the page flashes white before loading javascript (my eyes!).**
This commit stores the dark theme setting in a cookie, instead of the local store. This way the server can send the HTML with the correct data attribute, preventing the page from starting to draw the light theme for a few frames.
2. **Small space fix**
Before
After
3. **Change pagination style to fit better in the dark theme.**
Before
After
4. **Fix last_page check on index and alias_log.**
This correctly disables the next/previous button on those pages. (They currently allow you to go past the boundaries)
5. **Set input background to white for the light theme (looks better I think)**
Before
After
=> Frontend improvements

app/api/base.py, server.py, templates/error/405.html
Move API error handling. Dashboard currently does not show the HTML error page. Only return json if request URL starts with /api/.
Test with:
```
http https://app.simplelogin.io/dashboard/not_existing
http https://app.simplelogin.io/api/not_existing
```
=> Move api error handling to global error handler

app/api/views/auth.py, app/auth/views/activate.py, app/auth/views/fido.py, app/auth/views/forgot_password.py, app/auth/views/login.py, app/auth/views/mfa.py, app/auth/views/recovery.py, app/auth/views/reset_password.py, app/extensions.py, requirements.in, requirements.txt, server.py, templates/error/429.html
Based on #199 #203. 
Implementation for rate limiting, specified limit is per IP.
- Puts limit on endpoints like username/password authentication and mfa endpoints.
- Only counts 'bad requests', e.g. failed login attempt.
- I arbitrarily chose 10/min limit. Any thoughts? As it's only failed requests, we could possibly lower this. More complex limits are possible:
```
@limiter.limit("100/day;10/hour;1/minute")
```
Nginx snippet
```
server {
server_name  app.mydomain.com;
location / {
proxy_pass http://localhost:7777;
proxy_set_header X-Forwarded-For $remote_addr;
}
}
```
=> Implement rate limiting

app/dashboard/templates/dashboard/fido_setup.html
- disable form automatic submit when entering
- replace button by span to avoid automatic submit when clicking on the button on firefox
- check if key name is not empty
=> Fix fido setup not working on Firefox

app/dashboard/templates/dashboard/domain_detail/dns.html
When I was setting up SimpleLogin (cool stuff by the way), DKIM went wrong because the record ended up being converted to `dkim._domainkey.simplelogin.co.example.com` due to the lack to ending dot.
This PR proposes adding a `.` at the end of the Value in the DNS screen to hopefully prevent others from making my mistake.
Please note: I haven't tested this myself, haven't bothered setting up the Docker container yet.
=> Add dot after DKIM

app/dashboard/templates/dashboard/index.html
Choosing an icon for this is HARD. I ended up going with `fa-inbox` because it was generated because of an auto-generated email and I couldn't find any better icon on https://fontawesome.com/icons?d=gallery&m=free. However, if you have a suggestion, I'll gladly change it.
=> Show icon if address was autogenerated

app/models.py, tests/test_models.py
I sometimes get emails where the sender's name is the same as the email address. This causes the same info to be displayed twice. This code deduplicates it.
So, if you get an email like `From: example@example.com <example@example.com>` it should only display as `example@example.com <reply_address>` instead of `example@example.com - example@example.com <reply_address>`.
I hope this code and change is useful to you. Feel free to tell me if you want any changes.
=> Dedupe email address

Dockerfile
Remove the `vim`, `telnet` on production image
Other things to consider:
- Using smaller size Python image: python:3.7-alpine/python:3.7-slim
- Run as non-root user, ref: https://github.com/hexops/dockerfile#run-as-a-non-root-user
=> refactor(build): remove dependencies in production

app/api/views/export.py, app/dashboard/templates/dashboard/batch_import.html, job_runner.py, static/batch_import_template.csv
I noticed while looking at everything more that the import code always uses the default mailbox. This change adds the mailboxes of each alias to the export so that the correct mailboxes can be assigned during a batch import.
=> Export and import mailbox info with alias

README.md, example.env
When I was trying to install and test simple-login, I had an error with my `~/simplelogin.env`.
Reading back the README and the `example.env` I discovered that one parameter was missing in both making all the script failed (like `python init_app.py`)
I hope my little PR will help some other people that was like me and didn't know why it won't init 😄
=> Missing DKIM_PUBLIC_KEY_PATH in readme and example.env

README.md
Running docker in `sudo` mode is considered harmful.
It's recommended to run docker as non-root user to
minimize the security risks.
[0]: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
=> chore: remove sudo in running docker

app/dashboard/templates/dashboard/custom_alias.html
Hi, I love this product and can't do without it now! Thank you for bringing me the idea of email aliases.
This PR makes the "Create" button on ["Create New Custom Alias" page](https://app.simplelogin.io/dashboard/custom_alias) focusable by a keyboard. Technically, this just replaced `<span>` with `<button type="button">`. It's not `type="submit"`, so that browsers don't natively submit.
The following figure shows what happens when I press Tab in the focused text area with the current implementation:
The focus jumps to the logo link.
Also, after this commit:
The button is focused, and the focus ring is displayed.
=> Make the "Create" button focusable with keyboard

app/dashboard/templates/dashboard/custom_alias.html
This PR is a revised version of #561, fixes [the problem](https://github.com/simple-login/app/pull/561#issuecomment-899102494
). 
The following scenarios works well on my local machine:
1. (Error) Click the "Create" button with the prefix and mailboxes empty.
2. (Error) Click the "Create" button with all mailboxes unchecked.
3. (Error) Click the "Create" button with the prefix empty.
4. (Success) Click the "Create" button with the prefix filled and mailboxes checked.
---
In #561, the Create button was not working due to an error caused by Bouncer. It was saying that  "submit is not a function", which means that Bouncer couldn't  refer  to  the submit method of the form.
This was caused by the button having "submit" in its id, which is similar to [this …
=> Re: Make the "Create" button focusable with keyboard

app/api/views/new_random_alias.py
As I understand the error message, "word or alias" makes no sense. "word or uuid" would be better
=> fixed wrong description of error

app/api/views/auth_mfa.py, app/auth/views/mfa.py, app/auth/views/recovery.py, app/config.py, app/email_utils.py, templates/dashboard/setting.html, templates/emails/transactional/invalid-totp-login.html, templates/emails/transactional/invalid-totp-login.txt
This PR adds notifications for invalid TOTP codes where the user has correctly entered their email and password.
This is what the email currently looks like:
This is just a draft though as we obviously do not want to send an email every time this happens, we'd need to implement some kind of rate limit (maybe 1 email per day). I'm wondering if send_email_with_rate_control is the best way to achieve this?
=> Invalid TOTP and recovery code email notifications

docs/ses.md
One of the issues I was having when setting up SimpleLogin was this missing package in my Ubuntu 20 installation. Took me quite some time to figure out where the issue was, so I figured it'd be good to include it in the instructions.
=> Add required package for authentication with AWS SES

app/dns_utils.py, tests/api/test_alias.py
This PR uses resolve() instead of query() to resolve DNS queries. It also removes the deprecation tag from tests, I don't see any point in deprecating a test? Is there a valid reason for this @nguyenkims?
=> Fix deprecation warnings.

app/config.py, app/dns_utils.py, example.env
This MR implements allows the to define which nameservers to use when performing DNS requests.
By default the Cloudflare nameservers (`1.1.1.1`) will be used, but if the server administrator wants to, they can be changed.
=> Make nameservers configurable

app/dashboard/views/notification.py, email_handler.py, templates/header.html, templates/notification/alias-disable.html
- mark a notification as read when user arrives on the notification page
- create a notification when an alias is disabled
- show "more" only when a notification has a title. 
- Show either notification title or message. 
- Use bold font when a notification isn't read
=> Improve notification

app/email/status.py, app/email_utils.py, app/models.py, email_handler.py, tests/example_emls/5xx_overwrite_spf.eml, tests/example_emls/no_spamd_header.eml, tests/test_email_handler.py, tests/test_email_utils.py
Mute 5XX return codes with 2XX codes when return-path domain fails SPF checks
=> Reduce backscatter by checking return-path domain SPF status

app/email_utils.py, email_handler.py
Instead of saving the modified email save the original envelope so we can try to reproduce the problem easily
=> Save original envelope for debugging

app/email_utils.py, tests/test_email_utils.py
Added missing `% 8` to the padding calculator and ensured in the tests that we're testing all possible paddings.
=> Calculate proper padding when decoding base32

pyproject.toml
This PR adds an attribute to the `pyproject.toml` file that allows simplelogin to be included as a dependency from other Python projects.
=> Allow SimpleLogin to be used as a dependency

app/auth/views/fido.py
Closes #929 
Cable is still not accepted in the webauthn spec but safari and crhome implement it. We can just remove the requirement since we don't know what's the proper transport for each credential because we're not saving it on creation.
=> Do not send the transports to the js part since we have not stored them previously

README.md, docs/ssl.md
If merged, this PR will:
- Improve readability of `docs/ssl.md`
- Adds a section on HSTS
- Link to SSL doc in README at the relevant point
- Removes outdated certbot installation technique which is no longer supported
Mitigates the likelihood of users (like me!) [footgunning themselves](https://github.com/simple-login/app/discussions/600)
Thanks @developStorm for helping identify the cause of my issue!
The only thing I'm not 100% confident with is which container instances need to be restarted for `simplelogin.env` changes to be fully propogated. I can tighten the phrasing if someone can confirm for me :)
=> Update SSL documentation

app/auth/views/proton.py
This PR adds a hook to the oauth's `fetch_token` process that prevents continuing the code execution if the Proton API response is not a `200 OK`
=> Add OAuth hook for checking the status code

poetry.lock
The current version "3.3.2" can't seem to be installed on mac
=> upgrade cryptography to 37.0.1

app/auth/views/proton.py, templates/auth/login.html
This PR allows the "Login with Proton" feature to preserve the `next` parameter so the user is redirected after a successful login.
=> Preserve next_url in oauth login

.github/workflows/main.yml
- Create docker container also on tag
- Only run the docker container creation once 
- Run the workflow on push and on PR creation so it's run only once when the PR is updated with new commits
=> GH Actions refactor

monitoring.py, pytest.ini, tests/test_monitoring.py
Before `smtp` and `smtpd` both counted as the same since they started with the same chars.
=> Fix: Track processes that start with the same chars independently (smtp vs stmpd)

templates/dashboard/directory.html
Prevent users from displaying unsanitized HTML code in the delete confirmation box
=> Fix: Sanitize directory name before displaying it to the user

app/auth/views/proton.py, app/dashboard/views/setting.py, app/proton/proton_callback_handler.py, tests/proton/test_proton_callback_handler.py
1. Make the ProtonCallbackHandler receive the `Partner` instance as a parameter, so it can be passed from the outside
2. Remove the references to the `get_proton_partner_id` in the `ProtonCallbackHandler`
3. Retrieve the Proton partner on the HTTP handler and pass it to the `ProtonCallbackHandler`
=> Receive partner as param in ProtonCallbackHandler

templates/dashboard/support.html
This is to avoid our CS team from generic questions.
=> Suggest user to use SL reddit for generic question

app/config.py, app/models.py, example.env, migrations/versions/2022_052516_2b1d3cd93e4b_update_partner_api_token_token_length.py, tests/models/test_partner_api_token.py
1. Add a migration for increasing the size of partner api tokens
2. Add a `PartnerApiToken.generate` method that takes care of generating api tokens, processing them and storing them into the database
3. Add a `Partner.find_by_token` method that allows retrieving a `Partner` instance given a raw `PartnerApiToken`.
=> Store hmaced partner api tokens

app/handler/provider_complaint.py, app/models.py
- In the case of deleted aliases, we no longer have the user so skip reporting the complaint back to the user
- For domain deleted ones, use the user orm relationship
=> Do not report complaints for deleted aliases

app/api/views/apple.py
This bug is reported by users not having their subscription renewal taken into account in SL.
As recommended in https://developer.apple.com/documentation/appstorereceipts/responsebody/receipt/in_app
=> use responseBody.Latest_receipt_info and not responseBody.Receipt.In_app

app/onboarding/__init__.py, app/onboarding/utils.py, app/onboarding/views/account_activated.py, app/onboarding/views/extension_redirect.py, tests/test_onboarding.py
This PR adds the following changes:
* Move the browser detection and extension links to a `app/onboarding/utils.py` file
* a `GET /onboarding/extension_redirect` endpoint that redirects the user to the extension link depending on their browser
=> Add extension_redirect endpoint

app/account_linking.py, app/models.py, app/proton/proton_callback_handler.py, tests/models/test_user.py, tests/proton/test_proton_callback_handler.py, tests/test_account_linking.py
1. Adds a new optional parameter `from_partner` for the user creation. When this parameter is set, it will not send any notification to the user nor give the user any trial period.
2. Set the parameter explicitly to False when logging in with Proton (the user has started the flow, so even if it's linked to a partner, it's not created by a partner)
=> Allow to create users from partner

static/style.css
Updated background on hover for the "Login with Proton" buttons in order to use the same as the Proton background
=> Fix hover color in login with proton button

templates/dashboard/pricing.html, templates/dashboard/setting.html
Rename last occurrences of `get_subscription` to `get_paddle_subscription`
=> Fix: Missing renamed methods

docs/upgrade.md
People should upgrade from 2.X.X (supposing some of them still have this version) to 3.4.0, then migrate to 4.X.X. It's more incremental and easier to follow for people upgrading from 3.4.0 (which should be the majority)
=> Updated version numbers on doc

app/dashboard/views/setting.py, templates/dashboard/setting.html
- On the Settings page, in case of having a subscription managed by a partner, show `Premium subscription managed by {{ partner_name }}`
=> Show premium subscription managed by partner

app/oauth/views/authorize.py, templates/oauth/authorize.html, tests/oauth/test_authorize.py
This PR performs the following changes on the OAuth part:
1. Always perform the check of the `redirect_uri`, even if the app is in "dev mode".
2. Add a reaffirmation for the user to make sure they trust the OAuth client before proceeding if it's in "dev mode".
=> Always check redirect_uri for oauth

app/dashboard/views/alias_contact_manager.py, server.py
- Skip sending the error to sentry. 
- Decorate the sentry errors with user id to be able to debug it
=> Sanitize the highlight contact id

app/api/views/user_info.py, app/config.py, app/models.py, docs/api.md, tests/api/test_user_info.py
- Old accounts will keep the old value (pending config change)
- To enable this change in prod, we need to:
- Add the new config
- Add the flag to current users in prod
- Redeploy
=> Restrict the number of free alias for new free users

Dockerfile
- We still test with python 3.9 for backwards compatibility
- We gain performance improvements of python 3.10
=> Update Dockerfile to use python 3.10

app/image_validation.py, tests/test_image_validation.py
Do not allow users to upload SVG images as profile images, so we can avoid having to detect if the SVG is a malformed one.
=> Do not allow SVG image uploads

app/extensions.py, tests/test_extensions.py
This PR changes how we are obtaining a the key for the rate limiting process.
- If the user is not authenticated, the request source IP is used.
- If the user is authenticated, the user ID is used.
=> Rate limiting depending on user authenticated status

app/account_linking.py, app/auth/views/proton.py, app/proton/proton_callback_handler.py, app/utils.py
This PR adds the following changes:
- Support for `next` in the "Link Proton account" OAuth flow
- Support for passing a `scheme` to the Proton login/link
- Fix a server error when re-linking a Proton account (user already had the same Proton account linked)
=> Support next with Proton Link

app/api/views/setting.py, app/api/views/user_info.py, app/auth/views/api_to_cookie.py, app/auth/views/proton.py, app/dashboard/views/setting.py, app/proton/utils.py, tests/api/test_user_info.py
This PR adds the following changes for making `Connect with Proton` available on mobile:
- `DELETE /api/setting/unlink_proton_account` for unlinking the Proton account from the API
- Add `connected_proton_address: Optional[str]` on the response of `GET /api/user_info`
- Fixes on the `/api_to_cookie` endpoint for ensuring we redirect the user even if they're already authenticated
- Fixes in the Proton OAuth callback for invalid flows
-
=> Fixes for connect with proton on mobile

app/auth/views/proton.py
This PR replaces an `Exception` being thrown if an unknown `action` is received when doing a "Login/Connect with Proton"
=> Do not crash if action is unknown

app/handler/provider_complaint.py
If the complaint is for a `DomainDeletedAlias` use `alias.email` directly
=> Fix: Use email directly for DomainDeletedAlias

templates/footer.html
- _Downloads_ instead of _Features_
- Deleted _-_ in the _open source_
- Made _open source_ a link
- Added missing comparisons (consistency with the main page)
- Fixed GitHub spelling
Basically made the footer consistent with the main page.
Also a side note, the Twitter handle isn't updated on the GitHub organization.
=> Corrections & consistent footer

app/email_utils.py, email_handler.py
In case an alias has multiple mailboxes that belong to several people, it's useful for other people to know when an email is sent *from* an alias, i.e. a mailbox has sent an email to a reverse alias.
=> Notify another mailbox about an email sent by a mailbox to a reverse alias

app/config.py, app/mail_sender.py
- Override only smtp port if set to the default smtp port when enabling TLS
- Set a timeout for postfix
=> Fix: Only override postfix port when enabling TLS if the port is set to be 25

app/email_utils.py, app/models.py, app/newsletter_utils.py, job_runner.py, server.py, templates/emails/base.html, templates/emails/com/newsletter.html, tests/jobs/test_send_proton_welcome.py
Will only be set if the `unsubscribe_oneclick` variable is set for the template to prevent normal transactional emails from having it
=> Fix: Set oneclick link for unsubscribe of the newsletter for tx emails

app/email_utils.py, app/models.py, app/newsletter_utils.py, job_runner.py, server.py, tests/jobs/test_send_proton_welcome.py
Search for the alias when sending the newsletter only
=> Fix: Return email in the get_communication_email always

Dockerfile
Thanks to @mlec1 for the fix :+1:
=> Fix: Use npm ci instead of install to prevent install different versions

email_handler.py
I'm using SimpleLogin with PGP encryption enabled for a while, and I'm struggling with one issue. As FROM header is not encrypted, I have selected option **No Name** in **Sender Address Format** for better security. However, I'm losing information who sent these emails, I think the best option is to modify the header to something like this:
Forwarded by SimpleLogin to <simplelogin_recipient> **from <sender_addess>** with \<subject> as subject
This PR implements this feature :)
=> Add sender to PGP message body

app/dashboard/views/custom_alias.py, app/mail_sender.py
This fixes this scenario:
- user A transfer an alias from his custom domain to user B
- user B deletes this alias
- user tries to create the alias but don't see the error mentioning that the alias should be restored from trash first.
=> Fix recreate alias from trash

static/js/utils/drag-drop-into-text.js, static/style.css, templates/dashboard/contact_detail.html, templates/dashboard/mailbox_detail.html
The drag and drop of a PGP public key file only worked on Safari. I added the missing event listeners to also make it work on Firefox and Chromium-based browsers.
For the client side validation of the PGP key file I also tried to verify the file based on its extension, because file.type can give different results based on different browsers' implementations.
For example for a file with the extension `.asc`:
- file.type returns "text/plain" on Safari
- file.type returns "" (empty string) on Firefox and Chromium
So if I didn't change this code:
https://github.com/simple-login/app/blob/66039c526bfeeb4ca60c834fe82337cff6eb9df7/static/js/utils/drag-drop-into-text.js#L11-L12
a user could upload an `.asc` file properly in Safari but would get an error notification on Firefox/Chromium.
Bonus: …
=> Fix drag and drop to upload PGP public key not working on Firefox and Chromium (but working on Safari)

static/js/index.js, templates/dashboard/index.html
The save/update buttons in the aliases page have been deleted and replaced by an auto save feature for:
- the alias description text area, automatically saved when the field loses focus
- the mailbox select option, automatically saved when checking an option
- the display name input, automatically saved when losing focus or pressing Enter
Just in case, I added the hint message "(automatically saved when you click outside the field)", displayed only when a field is in focus, but if you find the message unnecessary I can delete it.
I also improved the notification "Description|Mailbox|Display Name saved"  to "Description|Mailbox|Display Name saved **for {alias.email}**".
=> Replace save/update buttons with an auto save feature

static/js/index.js, templates/dashboard/index.html
The stats for aliases (amount, replies/sent etc...) will be hidden by default. They can be shown/hidden by toggling a button and this option is persistent between page refreshes (similar to how the Filters button works).
=> Add option to show/hide stats in aliases page

docs/api.md, templates/base.html, templates/dashboard/refused_email.html, templates/emails/transactional/bounce/bounced-email.html, templates/emails/transactional/bounce/bounced-email.txt.jinja2, templates/notification/bounce-forward-phase.html
- Fix a markdown syntax error that prevented a section of the API docs from formatting correctly
- `spam` is an uncountable noun in english - `spams` should not be used, but rather `spam emails` as in 
_"I get many spam emails"_ instead of _"I get many spams"_ or _"They send many spam emails"_ instead of _"They send many spams"_
=> Documentation clarification

app/jobs/export_user_data_job.py
Add the `password` field to the list of ignored fields during the export of user data. Even though it was hashed, it should not be exported anyways.
=> fix: remove user password from export user data

app/email/headers.py, app/models.py, email_handler.py, tests/example_emls/replacement_on_forward_phase.eml, tests/handler/test_preserved_headers.py
Preserver the `Authentication-Results` header if the original envelope is also added to the headers.
Set the setting to preserve the from in the headers to true by default.
=> Preserve original sender in the headers

templates/dashboard/support.html
=> Fix typo in placeholder text of form on support page

docs/ssl.md
_This PR adds the following text to the `ssl.md` documentation_:
For additional security, we recommend you take some extra steps.
[MTA-STS](https://datatracker.ietf.org/doc/html/rfc8461) is an extra step you can take to broadcast the ability of your instance to receive and, optionally enforce, TSL-secure SMTP connections to protect email traffic.
Enabling MTA-STS requires you serve a specific file from subdomain `mta-sts.domain.com` on a well-known route.
Create a text file `/var/www/.well-known/mta-sts.txt` with the content:
```txt
version: STSv1
mode: testing
mx: app.mydomain.com
max_age: 86400
```
It is recommended to start with `mode: testing` for starters to get time to review failure reports. Add as many `mx:` domain entries as you have matching **MX records** in your DNS …
=> Documented MTA-STS and TLSRPT

docs/ssl.md
_This PR adds the following text to the `ssl.md` documentation:_
For additional security, we recommend you take some extra steps.
[Certificate Authority Authorization](https://letsencrypt.org/docs/caa/) is a step you can take to restrict the list of certificate authorities that are allowed to issue certificates for your domains.
Create a **CAA record** that contains the following text: 
To verify if the DNS works, the following command
```bash
dig @1.1.1.1 mydomain.com caa
```
should return:
```
mydomain.com.	3600	IN	CAA	0 issue "letsencrypt.org"
```
=> Documented CAA

templates/dashboard/pricing.html
This PR updates information from Proton Unlimited plan (price and amount of calendars) and removes the text "15 email addresses/aliases" as users found it confusing with the text "Unlimited aliases" on the left.
=> Update pricing page text

app/errors.py, app/proton/proton_client.py, tests/proton/test_proton_client.py
This PR aims to solve a case where the Proton API returns an error indicating that the Proton account is not validated. Right now we're displaying an Internal server error, but this case could be gracefully handled.
With this PR we will now provide a user with a meaningful error message.
=> fix: handle Proton account not validated case

app/handler/unsubscribe_generator.py, tests/utils.py
Depending on the encoding the headers may come as a string or as a header. Treat them all as strings.
=> Fix: Handle email headers as strings if the are Header type

templates/dashboard/domain_detail/dns.html
When I was configuring my subdomain-based alias, I was wondering why it would not verify, even after waiting a day. But after playing a bit of whack-a-mole with my DNS settings, the proposed changes worked for me.
=> Closes #1883 Update dns.html to amend DKIM configuration instructions

docs/api.md
I believe this may refer to the [published version](https://github.com/simple-login/app/blob/master/docs/api.md#get-apiv5aliasoptions) and not the former version.
=> Correct alias options version in docs

templates/dashboard/custom_alias.html, templates/dashboard/mfa_setup.html, templates/dashboard/notification.html, templates/dashboard/support.html, templates/dashboard/unsubscribe.html, templates/emails/transactional/activation.txt
Fix https://github.com/simple-login/app/issues/1990
=> Small fixes

README.md
Add -traditional option to openssl genrsa to avoid Python DKIM library (dkimpy) error that prevents email from being sent:
dkim.asn1.ASN1FormatError: Unexpected tag (got 30, expecting 02)
Ref: https://bugs.launchpad.net/dkimpy/+bug/1708917
=> Generate working DKIM keys by adding -traditional flag and update NGINX instructions to avoid breaking certbot

app/models.py, templates/emails/com/onboarding/welcome-proton-user.html, templates/emails/com/welcome.html, tests/models/test_alias.py
If the default mailbox for an alias is also in the mailbox alias table, do not return it twice.
=> Fix: Dedup the list of mailboxes for an alias

app/api/views/user_info.py, app/config.py, app/dashboard/views/alias_contact_manager.py, app/models.py, templates/dashboard/alias_contact_manager.html, templates/emails/com/onboarding/welcome-proton-user.html, templates/emails/com/welcome.html, tests/api/test_user_info.py
Update the web app to hide the form if the user cannot create them and update the api endpoint to signal clients that the user cannot create reverse alias.
=> Do not allow free users to create reverse alias to reduce abuse

templates/footer.html
Currently the logo touches the separator
=> fix space issue on footer

.github/workflows/main.yml
Remove armv7 from build as poetry seems to error on build
Tested on personal repo
> [linux/arm/v7 stage-1 4/6] RUN pip install -U pip     && apt-get update     && apt install -y curl netcat-traditional gcc python3-dev gnupg git libre2-dev cmake ninja-build    && curl -sSL https://install.python-poetry.org | python3 -     && apt-get purge -y curl netcat-traditional     && poetry config virtualenvs.create false     && poetry install  --no-interaction --no-ansi --no-root     && apt-get purge -y libre2-dev cmake ninja-build    && apt-get clean     && rm -rf /var/lib/apt/lists/*:
89.53 
89.53 You can uninstall at any time by executing this script with the --uninstall option,
89.53 and these changes will be reverted.
89.53 
89.53 Installing Poetry (1.8.2)
89.53 Installing Poetry (1.8.2): …
=> ci: remove v7

app/config.py, event_listener.py, events/event_sink.py
This PR implements the HTTP event sink, for sending the sync events using an HTTP transport.
It also adds a new config that allows to disable the SSL verification for that request (only if defined).
=> feat: implement HTTP event sink

app/models.py, event_listener.py, events/event_source.py, events/runner.py, monitoring.py
This PR adds some fixes for the event listener:
1. Commits the transaction after marking the event as taken. Otherwise in case of an error it would never add the `taken_time` value.
2. Allows the event_listener to reconnect to postgres, in order to improve resiliency against DB failures.
3. Adds a function to log the sync_events to be processed to the metrics server.
4. Make the `dead_letter` runner able to process events without the `mark_as_taken` returning true, so stuck events can be processed.
=> fix: event listener

app/models.py
Hello
I am writing to report a security vulnerability I discovered in the Simple Login service, specifically in the 2FA recovery code authentication mechanism. The issue allows an attacker to bypass 2FA using hashed recovery codes directly, potentially leading to unauthorized access if the database is previously compromised (ex: leak).
The vulnerability allows an attacker to bypass 2FA using hashed recovery codes stored in the database. If an attacker gains access to the database, they can use the hashed recovery codes to bypass 2FA, posing a significant security risk.
1. Create an Account: Register a new account on the Simple Login service.
2. Enable 2FA: Enable 2FA on the account to generate recovery codes.
3. Logout: Log out of the account.
4. Attempt Login: Log in with the correct …
=> [Security] Remediate 2FA bypass with hashed recovery code

app/config.py
When POSTFIX_TIMEOUT reading from env, it's default type is str, which will case an error
This PR converts it to int.
=> fix: convert POSTFIX_TIMEOUT to int

app/config.py, event_listener.py, events/event_source.py
This MR contains the following changes:
- Allow to configure a different DB_URI for the event listener. If a connection pool DB_URI is used, it may not forward the LISTEN/NOTIFY events properly. It defaults to the `DB_URI` in case it's not needed.
- Replace `id` with `user_id` in a for loop to avoid the linter warning.
=> chore: allow to define a different DB_URI for event listener

event_listener.py, events/event_debugger.py
This MR adds a couple of commands to the `event_listener.py` entrypoint that can be useful to debug pending sync_events.
All the remaining subcommands and behavior remain unaffected.
Get information about an event
```
$ python3 event_listener.py debug 39
- Created at: 2024-08-21T04:57:02.659400+00:00
- Updated at: 2024-08-21T05:45:15.835087+00:00
- Taken time: 2024-08-21T04:57:02.696738+00:00
- Retry count: 23
Event contents
- UserID: 12345
- ExternalUserID: abcdefghijkl==
- PartnerID: 5678
Content: alias_status_change {
alias_id: 4567
alias_email: "some@alias.test"
}
```
Run manually the processing of an event (and optionally deleting it in case of success)
```
$ python3 event_listener.py run 39 [--delete-on-success]
- Sending event 39 to WEBHOOK_URL
```
=> feat: add command to debug sync events

job_runner.py
Add a missing parameter on the `job_runner.py` when sending the pending aliases to be synced for a user
=> fix: specify default dispatcher in job runner

.github/workflows/main.yml, app/dashboard/views/mailbox.py, app/proton/proton_callback_handler.py, email_handler.py, oneshot/alias_partner_set_flag_and_clear_note.py, tests/proton/test_proton_callback_handler.py
- On new user login/link via partner trigger SL alias initial sync
- Do not close tx on rollback. This leaves dangling user object that fails afterwards
- Redirect to mailbox view instead of rendering the view to avoid requiring an object
- Script to update the alias flag and note once the note is no longer added
=> Sync on partner user creation + several fixes

app/alias_utils.py, app/events/generated/event_pb2.py, app/events/generated/event_pb2.pyi, app/jobs/event_jobs.py, app/models.py, proto/event.proto, tests/events/test_sent_events.py, tests/jobs/test_send_alias_creation_events.py
Also. homogeneized the names of the proto events. Some had `alias_` and some didn't. Since the events are all `AliasSomething` I've removed the `alias_` prefix where it was redundant
=> Send alias creation in proto

app/config.py, app/constants.py, app/custom_domain_validation.py, app/dashboard/views/domain_detail.py
1. Offer a new function that loads a dictionary from an env var
2. Allow to define partner domains (not in use yet)
3. Extracting logic from the controller into a service so it can be reused
4. Move the DMARC record to `app.constants`
=> feat: extract custom domain utils to a service

app/custom_domain_validation.py, app/dns_utils.py, templates/dashboard/domain_detail/dns.html, tests/test_custom_domain_validation.py, tests/test_dns_utils.py
1. Encapsulate all the DNS logic into classes that implement base class methods.
2. Remove global functions in favour of passed-on implementations (IoC).
3. Add tests to `app/custom_domain_validation.py` before extending the code.
=> chore: refactor dns to improve testability

app/config.py, app/custom_domain_validation.py, app/dashboard/views/domain_detail.py, app/models.py, templates/dashboard/domain_detail/dns.html, tests/test_custom_domain_validation.py
This PR adds the ability to define partner records and prefixes for custom domain validation.
It perorms the following changes:
1. Extract the `get_ownership_dns_txt_value` function from the model into a function of the `CustomDomainValidation`.
2. Remove the direct call from the template to the aforementioned function in order to pass the value from the controller.
3. Add the new configs that define the domain and the verification prefix for each partner.
4. Use these configs in the CustomDomainValidation, with fallbacks for the existing behaviour.
=> feat: allow to define partner records

events/event_source.py, monitoring.py
To restrict possible values we restrict app names that start with `sl-`
=> Add monitoring for app connections to the db

app/api/views/alias.py, app/contact_utils.py, app/dashboard/views/alias_contact_manager.py, app/models.py, email_handler.py, tests/api/test_alias.py, tests/dashboard/test_alias_contact_manager.py, tests/test_contact_utils.py
The same checks can later be re-used in other places
=> Move more contact creation logic to a single function

app/config.py, app/mailbox_utils.py
This PR adds a useful feature for testing environments, so we can predefine a static mailbox verification code via config. If not defined, the behaviour will match the previously existing one.
=> feat: allow override mailbox verification code

app/custom_domain_utils.py, app/dashboard/views/domain_detail.py, tests/test_custom_domain_utils.py
This PR extracts the `set_custom_domain_mailboxes` from the controller so we can import it as required and test it on isolation
=> chore: extract set_custom_domain_mailboxes from controller

app/config.py, app/custom_domain_validation.py, app/dashboard/views/domain_detail.py, app/dns_utils.py, app/email_utils.py, app/models.py, cron.py, templates/dashboard/domain_detail/dns.html, tests/test_custom_domain_validation.py, tests/test_dns_utils.py
⚠️ Please review with attention ⚠️ 
1. Move out logic from the `dns.html` template file into the controller, passing the values to be used instead of calculating them in the template.
2. Offer new functions that return the expected MX and SPF records on the `CustomDomainValidation` class.
3. Make use of the aforementioned functions during the MX and SPF verification process.
4. Encapsulate the MX records into a `MxRecord` class instead of a `Tuple[int, str]`. 
5. Adapt the tests accordingly to these changes and add some new ones.
=> fix: improve MX and SPF domain handling

app/email_utils.py, tests/test_email_utils.py
Currently if the mailbox email belongs to any custom domain we don't allow to create it but it should be denied only for SL domains.
=> Fix: Allow to create mailboxes for a custom domain if they are not SL domains

app/custom_domain_validation.py, app/dashboard/views/custom_domain.py, app/dns_utils.py, tests/test_custom_domain_validation.py
- clean unexpected records in SPF and DMARC validation
- Use `search=False` for TXT records
- Do not show custom domains pending deletion in dashboard
=> chore: DNS validation improvements

app/alias_utils.py, tests/dashboard/test_alias_transfer.py, tests/events/event_test_utils.py, tests/events/test_sent_events.py
When transferring an alias send events for:
- delete alias for source user
- create alias for target user
=> On alias transfer send the proper events

cron.py, crontab.yml
- Make cron retry failed jobs exponentially backing off
- Check hibp for premium users, not just paid
- Only poll apple subs that can be renewed and are near end of expiration
- Clean domains not verified and left to rot for a month
=> Several fixes

app/api/views/new_custom_alias.py
Adds a missing handling for a `None` `alias_prefix` value of the request
=> fix: missing null check for dict value

app/models.py, migrations/versions/2024_111315_842ac670096e_add_missing_indices_on_user_and_mailbox.py
This PR adds two missing indices:
- `users.default_mailbox_id`. This one was really important, as when deleting a mailbox it would cause a full-table scan for `users` in order to try to find a user with the `mailbox_id` that was going to be deleted.
- `mailbox.pgp_finger_print`
=> chore: add missing indices for user and mailbox

app/models.py, migrations/versions/2024_111512_0f3ee15b0014_add_missing_indices_for_fk_constraints.py
This PR adds missing indices that were used on FK constraints when performing `DELETE CASCADE`.
=> chore: add missing indices for fk constraints

app/mailbox_utils.py, email_handler.py, tests/test_email_handler.py, tests/test_mailbox_utils.py
Use the mail_from when receiving a mail to the reverse alias if the domain is aligned with the VERP email
=> Allow to use header from if domain is aligned with envelope

app/api/views/alias.py, app/api/views/new_custom_alias.py, app/models.py
This PR includes some fixes / improved error handling for some crashes we've seen on the production API.
=> fix: api crashes

app/log.py, app/request_utils.py, server.py
Log messages now include a request_id parameter across all the log messages of the same request in order to improve log searching
See the request_id after the PID
```
2025-01-28 14:53:09,827 - SL - DEBUG - 35908 - TaH0/qx5 - "/Users/carlos/code/simple-login/app/server.py:286" - after_request() -  - 127.0.0.1 GET /auth/login ImmutableMultiDict([]) 200, takes 0.07936620712280273
```
=> feat: add request_id in log

app/models.py, migrations/versions/2025_013114_97edba8794f8_index_cleanup.py
According to PGHero, this index is already covered by the `ix_email_log_user_id_email_log_id`
=> fix: remove duplicate EmailLog index

job_runner.py, tests/jobs/test_job_runner.py
By ensuring we only take a job transactionally we can have several job runners running in parallel to scale them up.
=> Allow several job runners to run in parallel

app/api/views/user.py, app/config.py, app/constants.py, app/custom_domain_utils.py, app/dashboard/views/batch_import.py, app/dashboard/views/delete_account.py, app/jobs/export_user_data_job.py, app/jobs/send_event_job.py, app/mailbox_utils.py, app/models.py, app/partner_user_utils.py, job_runner.py, tests/api/test_user.py, tests/jobs/test_delete_mailbox_job.py, tests/jobs/test_send_event_to_webhook.py, tests/models/test_user.py, tests/proton/test_proton_callback_handler.py, tests/test_mailbox_utils.py
This PR moves the job names out of the `config` module into a `JobType` enum in `constants`, as they are not configurable and so we trim down a bit the `config.py` file
=> refactor: move job names to enum in constants

app/email/headers.py, app/handler/unsubscribe_generator.py, tests/handler/test_unsubscribe_generator.py
If there's an original `List-Unsubscribe` header:
- Preserve original under `X-SL-Original-List-Unsubscribe`
- Create a `X-SL-Proxy-List-Unsubscribe` that will send the original unsub request from the alias
=> Preserve Unsubscribe header and create one that always unsubs via alias

app/constants.py, app/jobs/sync_subscription_job.py, job_runner.py, oneshot/schedule_sync_subscription_job.py, tests/jobs/test_sync_subscription_job.py
This PR adds a job and a command to schedule the User subscription sync job in a more efficient way. Instead of calculating the job payload and scheduling it, we now only schedule the user sync job, and once the job is executed the subscription details are fetched, ensuring we don't work with stale data.
=> feat: add job to schedule subscription sync

app/models.py, migrations/versions/2025_050611_87da368d282b_provider_complaint_fk.py
There was a missing ON DELETE CASCADE constraint on `ProviderComplaint`
=> fix: add missing on-delete-cascade constraint

app/mail_sender.py, cron.py, events/event_source.py, events/runner.py, job_runner.py, monitor/metric_exporter.py, monitor/upcloud.py
This small PR resolves the `logger.warn()` deprecation warnings:
```python
/home/runner/work/app/app/app/mail_sender.py:190: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
See [CI logs](https://github.com/simple-login/app/actions/runs/14863221267/job/41733318651#step:11:415) for more information.
=> fix: migrate to `logger.warning` usage

app/api/views/auth_mfa.py
This code change applies `parallel_limiter` to the MFA endpoint to prevent users from abusing it by sending multiple requests in parallel.
=> IDTEAM-4740: use parallel_limiter to prevent auth_mfa abusing.

app/api/serializer.py, app/api/views/alias.py, tests/api/test_alias.py
1. Add a filter on trashed aliases on the deprecated API endpoint
2. Add a missing commit call when moving an alias to trash
=> fix: commit alias deletion on API + add filter on trashed aliases in api

app/models.py, tests/test_alias_delete.py
When deleting a mailbox, if the user setting is set to send alias to the trash, this setting was not being taken into account
=> fix: mailbox deletion respects alias setting
