simple-login/app

.github/workflows/pythonpackage.yml
tests/test_models.py

@NinhDinh this PR adds also the "formatting check" to Github workflow. The formatter used in the project is https://github.com/psf/black

Add black ci

---

app/dashboard/views/custom_alias.py
app/utils.py

Just discovered some users are trying to get some nice alias suffix :).

make sure that user cannot use any suffix

---

app/dashboard/templates/dashboard/custom_domain.html
app/dashboard/templates/dashboard/directory.html
app/dashboard/views/custom_domain.py
app/dashboard/views/directory.py
app/dashboard/views/domain_detail.py
app/email_utils.py
app/models.py
email_handler.py
server.py
templates/emails/cannot-create-alias-directory.html
templates/emails/cannot-create-alias-directory.txt
templates/emails/cannot-create-alias-domain.html
templates/emails/cannot-create-alias-domain.txt

This PR handles the case when a user cancels his/her premium plan.
- They still have access to all aliases, domains & directories created before
- They no longer can create new domain or directory
- They can longer use the alias automatic alias creation thanks to directory or domain: an email will be sent to notify them.

Canceled premium

---

.github/workflows/main.yml
app/dashboard/templates/dashboard/directory.html
app/dashboard/views/directory.py
email_handler.py

Support `#` and `+` as directory separator.

Directory separator

---

README.md
app/api/__init__.py
app/api/views/auth_login.py
app/api/views/auth_mfa.py
tests/api/test_auth_login.py
tests/api/test_auth_mfa.py

This PR contains 2 endpoints targeted at the upcoming iOS app:
- /api/auth/login
- /api/auth/mfa
More endpoints are coming :).
cc @ntnhon

Api mobile

---

.env.example
app/api/views/alias_options.py
app/api/views/new_custom_alias.py
app/auth/views/register.py
app/config.py
app/dashboard/templates/dashboard/custom_alias.html
app/dashboard/views/custom_alias.py
app/dashboard/views/setting.py
app/email_utils.py
email_handler.py
tests/api/test_alias_options.py
tests/api/test_new_custom_alias.py
tests/env.test
tests/test_email_utils.py

Several alias domain

---

app/email_utils.py
email_handler.py
templates/emails/reply-must-use-personal-email.html
templates/emails/reply-must-use-personal-email.txt

Notify user if there's an attempt using their alias from an unknown email address

Notify user reply

---

app/auth/views/facebook.py
app/auth/views/github.py
app/auth/views/google.py
app/auth/views/register.py
app/dashboard/views/setting.py
app/email_utils.py
tests/test_email_utils.py

This PR is to make sure an email alias cannot be used as personal email

Check personal email

---

app/dashboard/views/alias_log.py
email_handler.py

- Order alias log by recency
- Update From header for forward-email if changed

Fix alias log

---

app/config.py
example.env
server.py

use another sentry project for the front-end with SENTRY_FRONT_END_DSN

---

README.md
app/api/views/alias.py
app/api/views/auth_login.py
app/api/views/auth_mfa.py
tests/api/test_alias.py
tests/api/test_auth_login.py

- DELETE /api/aliases/:alias_id
- POST /api/aliases/:alias_id/toggle
- GET /api/aliases/:alias_id/activities

Add some alias endpoints for API

---

app/config.py
app/dashboard/templates/dashboard/mailbox_detail.html
app/paddle_utils.py
email_handler.py
templates/emails/transactional/spf-fail.html
templates/emails/transactional/spf-fail.txt

- Alert user when SPF fails
- Some Refactorings

Alert user when SPF fails

---

app/dashboard/templates/dashboard/domain_detail/dns.html
app/dashboard/templates/dashboard/index.html
static/assets/css/darkmode.css
static/assets/js/core.js
templates/base.html
templates/header.html

This PR
* Using CSS variable as a solution
* The new dark mode CSS is now live in another file so that upgrading
dashboard.css doesn't affect the dark mode itself
* Used a naive dark mode controller by client javascript. No persistence
states is stored in the backend at the moment

Dark mode implementation

---

email_handler.py

1. Replacing reverse alias needs to be done before DKIM signing.
2. Replace with contact.website_email, not alias.email

Fix reverse alias replacement

---

app/alias_utils.py
app/dashboard/templates/dashboard/directory.html
app/dashboard/views/directory.py
app/models.py

Able to set mailboxes for directory

Directory mailboxes

---

app/dashboard/views/custom_domain.py

https://github.com/simple-login/app/issues/250

avoid adding a built-in domain as custom domain

---

app/alias_utils.py
app/models.py
server.py
shell.py

Fix deleted alias not putting to its correct trash

Fix alias trash

---

app/config.py
app/dashboard/templates/dashboard/refused_email.html
email_handler.py
example.env
requirements.in
requirements.txt
templates/emails/transactional/spam-email-reply-phase.html
templates/emails/transactional/spam-email-reply-phase.txt

Use SpamAssassin server to check whether an email is spam.

Enable Spamassassin server

---

README.md

Added instructions to update 'myuser' and 'mypassword' where appropriate.

Update README.md (Self-hosted instructions)

---

README.md

"loose" is the opposite of "tight", "lose" is the opposite of "acquire".

Readme spelling correction.

---

.github/workflows/main.yml
.gitignore
poetry.lock
pyproject.toml

Hi,
I was wondering how to contribute to simple login and thought about writing tests but without coverage reports its not easy to find where to start !
This PR:
This last point is of course debatable, as test coverage is not an absolute indicator of code quality, but, IMHO, 60% is a bit low, and it would be nice to reach 80% one day.

Measure test coverage

---

app/api/__init__.py
app/api/views/export.py
app/dashboard/views/setting.py
docs/api.md

Fixes #374 (mostly, no import)

Add export endpoints

---

README.md

This will make it easier to be read 🎉

Enable nginx config block syntax highlight in README.md

---

cron.py

Accidentally got rid of this during some refactor. Relevant to https://github.com/simple-login/app/pull/472#issuecomment-845289837

Update hibp_last_check on succesful HIBP check

---

app/dashboard/templates/dashboard/index.html

https://haveibeenpwned.uservoice.com/forums/275398-general/suggestions/43456596-offer-a-direct-link-to-an-account-s-breaches

Add direct link to HIBP pwned info

---

email_handler.py

Trying to fix last commit to master.
https://github.com/simple-login/app/runs/4072170008?check_suite_focus=true

Remove unused import

---

templates/dashboard/support.html

Show a warning toast if the user cannot create more aliases. The last one is alredy kept in the form.

Show a warning if the user cannot create more aliases

---

app/oauth/views/authorize.py

Currenty we allow that route to be executed by non authenticated users.

Only allow authenticated and enabled users to accept a OAuth post request

---

static/js/utils/drag-drop-into-text.js
templates/dashboard/contact_detail.html
templates/dashboard/mailbox_detail.html

The UI is not great but it's functional. Any suggestions on how to improve the UI?

Allow drag and drop of keys into the text area

---

templates/base.html

Enable plausible goal tracking.

Use plausible outbound link tracking

---

app/admin_model.py

This MR makes a change that allows an admin to update a ManualSubscription via the web admin interface.

Allow to edit manual subscription

---

app/email_utils.py

This PR should fix the issue raised in https://github.com/simple-login/app/issues/418#issuecomment-1066210283

decode, replace and encode for base64 encoding

---

app/auth/views/fido.py
app/auth/views/github.py
app/auth/views/mfa.py
app/auth/views/recovery.py
app/dashboard/views/enter_sudo.py
app/oauth/views/authorize.py
app/utils.py
pytest.ini
tests/oauth/test_authorize.py
tests/test_utils.py

Take also into account urls that do not specify a scheme

Properly validate //host.com urls 

---

app/email_utils.py
tests/test_email_utils.py

to avoid AC_FROM_MANY_DOTS SpamAssassin rule

use _ instead of . in reverse alias

---

email_handler.py
tests/api/test_alias.py
tests/api/test_new_custom_alias.py
tests/api/test_new_random_alias.py
tests/api/test_serializer.py
tests/api/test_setting.py
tests/auth/test_login.py
tests/dashboard/test_alias_contact_manager.py
tests/dashboard/test_custom_alias.py
tests/dashboard/test_custom_domain.py
tests/dashboard/test_index.py
tests/dashboard/test_subdomain.py
tests/dashboard/test_unsubscribe.py
tests/test_email_handler.py
tests/test_email_utils.py
tests/utils.py

cc @ntnhon this will add the alias to the To: header if needed

add alias to To: header if it isn't included in To and Cc header

---

app/config.py
email_handler.py
tests/test_email_handler.py
tests/test_email_utils.py

This prepares the change of noreply@simplelogin.co to noreply@simplelogin.io

able to handle several noreply addresses

---

app/api/views/alias.py
docs/api.md
tests/api/test_alias.py

add new parameter disabled in /GET /api/v2/aliases

---

app/email/spam.py
app/email_utils.py
app/handler/dmarc.py
app/mail_sender.py
app/message_utils.py
email_handler.py
tests/test_email_utils.py
tests/test_message_utils.py

Allow sending messages from a background thread when enabled.

Allow sending messages in a background thread

---

app/utils.py
tests/test_utils.py

This PR fixes a potential open redirect vulnerability.

Fix open redirect

---

templates/dashboard/setting.html

when user doesn't have default domain for alias, display "Not Selected" to avoid confusion

handle case user doesn't have default domain for alias

---

.github/changelog_configuration.json
.github/workflows/main.yml

This PR aims to fix the slack notification error.

Fix Slack notification

---

app/email_utils.py
app/mail_sender.py
pyproject.toml
tests/handler/test_provider_complaints.py

- Allow testing mails by storing them in mem so they can retrieved in the tests
- Add migrations and templates in pyproject

Allow testing sent mails and add migrations and templates in app bundle

---

app/onboarding/__init__.py
app/onboarding/views/index.py
app/onboarding/views/setup_done.py
templates/onboarding/final.html
templates/onboarding/index.html
templates/onboarding/setup_done.html

1. Adds a new `setup_done` page for the onboarding process that will trigger the "extension setup" flow on the new extension (PR for the extension [can be found here](https://github.com/simple-login/browser-extension/pull/134))
2. Changes the `next` parameter for the buttons on the first onboarding page.

Adapt extension setup

---

templates/header.html
templates/menu.html

- remove New mention on Subdomain
- do not show SIWSL and Apps page
- move api keys page to header

Menu optimize

---

templates/header.html

add mention about the limit of 15 aliases into the header

---

app/config.py
app/mail_sender.py
tests/handler/test_provider_complaints.py
tests/test_mail_sender.py

- Added a config SAVE_UNSENT_DIR to specify where to keep the unsent messages
- Added a method to save the messages to disk if sending fails for some reason
- Added method to load them from disk

Save unsent emails to disk to be resent later

---

docs/api.md

Make endpoint list easier to navigate. Preview here: https://github.com/ntnhon/app/blob/patch-1/docs/api.md

Add hyperlinks to endpoints in api.md

---

email_handler.py
templates/dashboard/notification.html
templates/notification/cycle-email.html

Create a notification when there's a cycle email.

Notify user cycle email

---

app/auth/views/forgot_password.py
app/dashboard/views/pricing.py

- Fix: rate limit marker was never called if successful in forget password route
- Fix: missing rate limit in coinbase_checkout

Add missing rate limits

---

job_runner.py

Missing elif instead of else triggered error that ended up in sentry

Fix: logic failed the onboarding-1 job

---

server.py

The corresponding subscription will be updated to reflect the refund.

handle subscription_payment_refunded event

---

app/utils.py
tests/test_utils.py

This PR fixes another redirect edge-case and adds a new test for preventing regressions

Fix double backslash open redirect

---

templates/auth/register.html

This PR adds the Proton logo to the sign up page's "Login with Proton" button.

Add Proton logo to sign up page

---

app/account_linking.py
app/admin_model.py
app/auth/views/proton.py
app/config.py
app/dashboard/views/billing.py
app/dashboard/views/coupon.py
app/dashboard/views/delete_account.py
app/dashboard/views/lifetime_licence.py
app/dashboard/views/pricing.py
app/dashboard/views/setting.py
app/models.py
app/proton/proton_callback_handler.py
app/proton/utils.py
cron.py
init_app.py
templates/emails/transactional/double-subscription-partner.html
templates/emails/transactional/double-subscription-partner.txt.jinja2
tests/email_tests/test_rate_limit.py
tests/proton/test_proton_callback_handler.py
tests/test_account_linking.py
tests/test_models.py

Send an email once to users that have a subscription and get upgraded by a partner.

Send email to users with a subscription and a partner plan upgrade

---

app/dashboard/views/pricing.py
static/style.css
templates/dashboard/pricing.html

After click to show sl upgrades

Propose upgrade proton account for proton partner users without paid mail plan

---

app/dashboard/views/pricing.py
templates/dashboard/setting.html

just renaming and run pycharm refactor on a html file

small refactoring

---

templates/dashboard/alias_log.html
templates/dashboard/index.html

The current one:
The new design:

add 14 days mention and use same stats design for alias activity page

---

app/auth/views/fido.py
app/auth/views/login_utils.py
app/dashboard/views/enter_sudo.py
app/internal/__init__.py
app/internal/exit_sudo.py
templates/dashboard/enter_sudo.html

Allow to login with proton to enter sudo mode

---

server.py

fix https://sentry.io/organizations/simplelogin/issues/3370469626/?alert_rule_id=2478639&alert_timestamp=1656988438946&alert_type=email&environment=production&project=1868546&referrer=alert_email

fix refund callback

---

app/email_utils.py

Also strip surrounding `'` and `"`

Fix: Add more weird encodings to the known encoding list

---

templates/dashboard/refused_email.html
templates/dashboard/setting.html

- improve wording
- show bounce or quarantine badge

distinguish between bounce and quarantine

---

app/auth/views/proton.py

This PR implements a `mode` parameter for the Login with Proton.
The main reason for this PR is for implementing the "Login with Proton" on the Android app.
It can have the following values:
* `apikey`: After the callback has been called, a redirect to `auth.simplelogin://callback?apikey=YOUR_API_KEY_HERE` will be returned to the client.
* `session`: The already existing behaviour.
If no value is passed for mode `session` will be used.

Implement mode for Login with Proton

---

app/auth/views/change_email.py
tests/auth/test_change_email.py

After an email change, remove all password reset codes.

Remove ResetCodes after email change

---

README.md

Merge pointing to 4.6.2-beta instead.

mitigate dns issue with dnsbl

---

example.env

Correction of the port assigned to PostGresql from '35432' to '5432'

DB port correction

---

cron.py
email_handler.py
templates/emails/transactional/invalid-mailbox-pgp-key.txt.jinja2

- cron job to check if pgp key is invalid
- check key validity first before using pgpy

Handle invalid pgp key

---

templates/dashboard/alias_contact_manager.html
templates/dashboard/alias_log.html
templates/dashboard/index.html

Fix: Spelling

---

app/email_utils.py
tests/test_email_utils.py

should fix https://sentry.io/organizations/simplelogin/issues/3563106404/?alert_rule_id=2478639&alert_timestamp=1662404226476&alert_type=email&environment=production&project=1868546&referrer=alert_email

handle case msg is string in replace()

---

app/api/views/user_info.py
app/auth/views/logout.py
app/session.py
server.py

This prevents somebody from storing an old cookie and being able to access the user data.

Store session in redis if redis is enabled

---

app/session.py

This PR adds support for Redis Sentinel to the RedisSessionStore.
The code for extracting the master and replica from Sentinel has been extracted from here: https://github.com/alisaifee/limits/blob/106e74f2b239c2fe4622fb15e2fa5594c242b9fb/limits/storage/redis_sentinel.py

Allow RedisSessionStore to connect to sentinel

---

app/custom_domain_validation.py
app/dashboard/views/domain_detail.py
templates/dashboard/domain_detail/dns.html

Have custom domains set up:
- dkim._domainkey.domain.com
- dkim02._domainkey.domain.com
- dkim03._domainkey.domain.com
So we can rotate dkim keys if needed.

Have custom domains set up multiple dkim records to be able to rotate keys

---

app/auth/views/activate.py
app/auth/views/fido.py
app/auth/views/forgot_password.py
app/auth/views/login.py
app/auth/views/mfa.py
app/auth/views/recovery.py
app/auth/views/reset_password.py
app/config.py
app/dashboard/views/support.py
app/extensions.py
tests/api/test_import_export.py
tests/api/test_new_custom_alias.py
tests/api/test_new_random_alias.py
tests/conftest.py
tests/dashboard/test_api_keys.py
tests/dashboard/test_custom_alias.py
tests/dashboard/test_directory.py
tests/dashboard/test_index.py
tests/test_extensions.py
tests/test_models.py

- disable rate limit during test
- randomize data in test
- support non-empty db in test

remove deduct_limit as it has no effect

---

app/mail_sender.py
cron.py
crontab.yml
tests/test_mail_sender.py

If we fail to contact postfix, store the mails locally and try to re-deliver them.

Feat: Re-deliver mails 

---

templates/base.html

show black friday banner

---

app/dashboard/views/custom_domain.py
app/dashboard/views/directory.py
app/dashboard/views/mailbox.py
app/dashboard/views/subdomain.py

Ensure parallel limit for 
- custom domains
- subdomains
- directories
- mailboxes

Added parallel limiting to several routes

---

docs/api.md

the param `mode` has to be passed in the query

Update docu for /api/alias/random/new

---

.gitignore
Dockerfile
app/api/views/mailbox.py
app/dashboard/views/mailbox.py
docs/api.md
job_runner.py
templates/dashboard/mailbox.html
tests/jobs/test_delete_mailbox_job.py

Improvement on https://github.com/simple-login/app/pull/1457 
I had to do it in a different MR because I can't push to @mlec1 's branch

Tranfer aliases to a new mailbox when deleting mailboxes

---

README.md
app/api/views/mailbox.py
app/dashboard/views/mailbox.py

Try to fix based on the comment of @nguyenkims

Fix delete alias mlec

---

email_handler.py
tests/test_email_handler.py

We canonicalize emails on register for gmail and proton. We need to accept messages from the non canonical versions and map to the expected users. If there's a user with a non-canonical email with exact match we match to that otherwise it should match to the canonical version.

Fix: Allow receive email from non-canonical sources

---

app/account_linking.py
app/email/status.py
app/errors.py
email_handler.py
tests/test_email_handler.py
tests/test_utils.py
tests/utils.py

We don't allow to use aliases as mailbox. If that happens break the loop in the email_handler

Break using an alias as a mailbox loop in the email_handler.py

---

templates/dashboard/pricing.html

This new pricing page has been redesigned from scratch and also includes a FAQ section. The text of the list of features and FAQ questions/answers are taken from [https://simplelogin.io/pricing](https://simplelogin.io/pricing).
Feel free to edit the text.
Also for the formatting I ran the command `poetry run djlint --reformat templates` but it removed the indentation, I don't know if that could be an issue.

Redesign new pricing page

---

email_handler.py

even if the domain cannot be used any more for contact creation

Fix: Allow contacts created with a domain to be delivered

---

app/dashboard/views/coupon.py
tests/dashboard/test_coupon.py

Ensure transactionally that coupons are only used once.

Ensure coupons are only used once

---

app/dashboard/views/setting.py

(cherry picked from commit e875f1dd40fe726f6e83aaa833f65eb9e10f7e94)

Fix: use incorrect model to access profile picture path

---

app/dashboard/views/mailbox.py

Ensure that the mailbox verification also check that the mailbox email has not been modified

Fix: Send also mailbox email to verify so that mailbox changes are not allowed

---

local_data/words.txt

Fix https://github.com/simple-login/app/issues/1905

Remove sensitive words

---

app/account_linking.py
tests/test_account_linking.py

When creating via partner:
- Link with canonical email if it exists
- If not create the user account with the canonical email

Creating account via partner also canonicalizes email

---

app/api/views/alias.py
app/dashboard/views/index.py

The index endpoint makes a heavy query.

Rate limit index endpoint

---

server.py
templates/base.html
templates/dashboard/pricing.html

Stop showing the BF promo Dec 1st midnight.

Show BF banner until end of promotion

---

local_data/test_words.txt
local_data/words.txt

Fix https://github.com/simple-login/app/issues/1982

Remove sensitive words 

---

templates/footer.html
templates/menu.html

Fix https://github.com/simple-login/app/issues/1998

Small fixes due to SL moving to Switzerland 

---

templates/emails/com/onboarding/welcome-proton-user.html
templates/emails/com/onboarding/welcome-proton-user.txt.jinja2
templates/emails/com/welcome.html
templates/emails/com/welcome.txt

Fix https://github.com/simple-login/app/issues/2000

small fixes

---

templates/header.html

Fix a bug introduced in 49b67324997487f8b5e52612f7115de7d11cbf17 which was causing a layout issue on pages where the header is present due to a missing `</div>`.

Fix dropdown item in header

---

tests/auth/test_login.py

- Added comments to each test function to provide clear documentation of the test steps.
-  Comments detail the purpose of each test, the actions taken, and the expected outcomes. 
- Improved readability and maintainability of the test suite. 
- No changes in functionality; only added comments for better code understanding.

Added comments to test_login.py

---

.github/workflows/main.yml

Add arm64 images to ci pipeline

ci: add arm docker images

---

app/admin_model.py
app/dashboard/views/mailbox_detail.py

It fixes https://github.com/simple-login/app/issues/2101

Fix admin loop

---

events/event_sink.py
events/runner.py

Improve error handling on event sink

Improve error handling on event sink

---

app/proton/utils.py

Log when a user unlinks the account from a partner

Log when a partner user is unlinked

---

app/auth/views/register.py

(cherry picked from commit dd09297bead4ea27731ac3bd60fcf2a3e7001268)

Only allow latest activation code to be used

---

README.md

Enhance Markdown for highlight **DISABLE_REGISTRATION** and **DISABLE_ONBOARDING** param in simplelogin.env .

Enhance Markdown for highlight DISABLE_REGISTRATION and DISABLE_ONBOARDING param in simplelogin.env

---

local_data/words.txt

@nguyenkims please take a look

remove “shady” words

---

app/custom_domain_validation.py

(missing code from the previous PR)

feat: allow to define partner records

---

app/events/event_dispatcher.py

This PR disables the whitelisting for event for restricted users

feat: disable whitelist events

---

app/mailbox_utils.py

fix: allow override mailbox verification code

---

.github/workflows/main.yml
app/api/views/auth.py
app/api/views/user_info.py
app/auth/views/login.py

To make the change we need to make sure that it's not set to None to just delete the picture.

Only change the profile picture if data is sent

---

server.py

Record a newrelic event for every HTTP response, containing the status code

feat: record newrelic event for http status code

---

app/auth/views/login.py
app/dashboard/views/account_setting.py
cron.py
templates/admin/email_search.html

- Fix login oracle timing issues to avoid trying to guess if users exist by timing responses
- Run HIBP for premium users and not just paid
- Add premium and paid in the admin panel

Several fixes

---

app/api/views/new_custom_alias.py

Add missing type check to prevent runtime errors

fix: add type check on create custom alias api

---

app/jobs/send_event_job.py
oneshot/schedule_sync_user_job.py

This PR adds a script to schedule "sync user plan" jobs

feat: add script to send sync user jobs

---

app/alias_delete.py
app/dashboard/views/alias_trash.py
app/errors.py
app/models.py
tests/test_alias_delete.py

Make sure user has enough alias quota to restore aliases

feat: alias restore check quota

---

Dockerfile
app/api/views/alias.py
app/api/views/custom_domain.py
app/api/views/mailbox.py
app/api/views/new_custom_alias.py
app/api/views/new_random_alias.py

- Update Docker file to force CMAKE to support 3.5
- Apply the rate limit after auth so we rate-limit by userID
- Add debug statements

Update rate limit to take into account user ID with several fixes

---

app/admin_model.py
app/models.py
templates/admin/custom_domain_search.html

This MR adds an action that will make it possible to remove custom domains from the Custom Domain Search page on the admin panel.

feat(admin): allow to remove custom domain

---

oneshot/schedule_sync_subscription_job.py

- Proper calculation of time
- Remove intermediate flushes use a single commit in batches of 100 to speed up inserts

schedule job script fixes

---

oneshot/schedule_sync_subscription_job.py

Fix potential division by zero errors

fix: time calculation division check

---

job_runner.py

Wrap the execution of the `job_runner` in a method annotated with `@newreilc.agent.background_task()` so a newrelic transaction is started and events are actually sent by the agent

fix(job-runner): add newrelic annotation to job runner

---

app/auth/views/login_utils.py
templates/admin/email_search.html

- Rotate the session id just after login to prevent session re-use
- Add delete_on user information on the admin panel

Rotate the session just after login

---

app/admin_model.py
app/models.py
templates/admin/email_search.html

* Adds a button in the admin panel to stop a scheduled user deletion + the corresponding AdminAuditLog entry
* Adds a section in the admin panel to update the user subdomain quota + the corresponding AdminAuditLog entry
* Adds the ability to perform lookups based on `PartnerUser.external_user_id` directly

feat(admin): admin panel improvements

---

.github/workflows/main.yml
app/admin_model.py
pyproject.toml
server.py
templates/admin/mailbox_search.html
uv.lock

Admin panel mailbox search
